%YAML 1.2
---
# Toit Package File.
# TODO:
# - Clear the example from comments.

# name: YOUR_PACKAGE_NAME
# version: 0.0.0
# author: 'e.g., John Doe'
# license: copyright
# url: Home page
# description: 'Some descriptions...'
# dependency:
#   package:
#     - name: PACKAGE_NAME
#       version: 0.0.0
#     ...
